# Generated by Django 5.1 on 2024-08-16 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttributeName",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nazev", models.CharField(blank=True, max_length=255, null=True)),
                ("kod", models.CharField(blank=True, max_length=255, null=True)),
                ("zobrazit", models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("hodnota", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("obrazek", models.CharField(max_length=255)),
                ("nazev", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("cena", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "is_published",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("mena", models.CharField(blank=True, max_length=255, null=True)),
                ("nazev", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "published_on",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "nazev_atributu_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="task.attributename",
                    ),
                ),
                (
                    "hodnota_atributu_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="task.attributevalue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Catalog",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nazev", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "attributes_ids",
                    models.ManyToManyField(blank=True, to="task.attribute"),
                ),
                (
                    "obrazek_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="task.image",
                    ),
                ),
                ("products_ids", models.ManyToManyField(blank=True, to="task.product")),
            ],
        ),
        migrations.CreateModel(
            name="ProductAttributes",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="task.attribute",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="task.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nazev", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "obrazek_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="task.image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="task.product",
                    ),
                ),
            ],
        ),
    ]
